permissions:
  use: "bettermsg.use"
  reply: "bettermsg.reply"
  use-color: "bettermsg.color"
  reload: "bettermsg.reload"


### EXPERIMENTAL FEATURES: This features are not fully tested and may not work as expected! ###
# DONT REQUEST SUPPORT IF THIS IS TRUE!
use-displayname: false