name: BetterMSG
version: '${project.version}'
main: dev.larrox.bettermsg.BetterMSG
api-version: '1.20'
author: Larrox
folia-supported: true
commands:
  msg:
    permission: BetterMSG.use
    description: send a private message to a player
    usage: /msg <Player> <Message>
    aliases:
      - whisper
      - w
      - dm
      - pm
      - tell
  reply:
    permission: BetterMSG.reply
    description: fast reply command
    usage: /reply <nachricht>
    aliases:
      - r
      - rply
      - antworten
      - anwser
  reloadmsg:
    permission: BetterMSG.reload
    description: reload the config.yml
    usage: /reloadmsg
    aliases:
      - rlmsg
      - rlbettermsg
      - reloadbettermsg