name: BetterMSG
version: '${project.version}'
main: dev.larrox.bettermsg.BetterMSG
api-version: '1.20'
author: Larrox
folia-supported: true
commands:
  msg:
    permission: BetterMSG.use
    description: send a private message to a player
    usage: /msg <Player> <Message>
    aliases:
      - whisper
      - w
      - dm
      - pm
      - tell
  reply:
    permission: BetterMSG.reply
    description: fast reply command
    usage: /reply <nachricht>
    aliases:
      - r
      - rply
      - antworten
      - anwser
  bettermsg:
    permission: BetterMSG.maincmd
    description: maincommand
    usage: /bettermsg <subcommand>
    aliases:
      - bmsg
      - betterwhisper
      - betterw
      - betterdm
      - betterpm
      - bettertell
      - betterreply
      - betterr

permissions:
    BetterMSG.use:
        description: Allows the player to use the /msg command
        default: true
    BetterMSG.reply:
        description: Allows the player to use the /reply command
        default: true
    BetterMSG.color:
        description: Allows the player to use colors in messages
        default: op
    BetterMSG.reload:
        description: Allows the player to reload the plugin configuration
        default: op