name: BetterMSG
version: '${project.version}'
main: dev.larrox.bettermsg.BetterMSG
api-version: '1.20'
author: Larrox
commands:
  msg:
    permission: BetterMSG.use
    description: Sende geheim eine Nachricht an einen Spieler
    usage: /msg <Spieler> <Nachricht>
    aliases:
      - whisper
      - w
      - dm
      - pm
      - tell
  reply:
    permission: BetterMSG.reply
    description: Antworte schnell auf die Letzte nachricht die dir gesendet wurde
    usage: /reply <nachricht>
    aliases:
      - r
      - rply
      - antworten
      - anwser
  reloadmsg:
    permission: BetterMSG.reload
    description: Lade die config.yml neu
    usage: /reloadmsg
    aliases:
      - rlmsg
      - rlbettermsg
      - reloadbettermsg